version: "3.8"
services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    container_name: postgresDB
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin@admin.com
      POSTGRES_PASSWORD: plant172839
      # POSTGRES_DB: test_db
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: plant172839
    ports:
      - "5050:80"
